MONGODB_HOST: mongodb-{{ env }}.gdaws86s.fun # mongodb-dev.daws86s.fun
REDIS_HOST: redis-{{ env }}.gdaws86s.fun
CATALOGUE_HOST: catalogue-{{ env }}.gdaws86s.fun
CART_HOST: cart-{{ env }}.gdaws86s.fun
USER_HOST: user-{{ env }}.gdaws86s.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.gdaws86s.fun
MYSQL_HOST: mysql-{{ env }}.gdaws86s.fun
SHIPPING_HOST: shipping-{{ env }}.gdaws86s.fun
PAYMENT_HOST: payment-{{ env }}.gdaws86s.fun